### ISSUE TITLE
Requesting explanation of apparent problem with syntax in TaylorSeries

### ISSUE THREAD

**Issue by jman87** [JuliaDiff/TaylorSeries.jl#114]
Hi all, fairly new Julia user here, and just started trying to use the TaylorSeries package today. I have looked through all the examples I could find online and now am trying to expand a function like this:

f(x,y) = 1 / (x^2 + y^2)  about x0=1, y0=1

Based on the examples, here is the code I have tried so far (which isn't giving the correct answer):

~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using TaylorSeries

julia> x, y = set_variables("x y")
2-element Array{TaylorSeries.TaylorN{Float64},1}:
  1.0 x + 𝒪(‖x‖⁷)
  1.0 y + 𝒪(‖x‖⁷)

julia> x = x-1
 - 1.0 + 1.0 x + 𝒪(‖x‖⁷)

julia> y = y-1
 - 1.0 + 1.0 y + 𝒪(‖x‖⁷)

julia> f = (x^2 + y^2)^(-1)
 0.5 + 0.5 x + 0.5 y + 0.25 x² + 1.0 x y + 0.25 y² + 1.0 x² y + 1.0 x y² - 0.125 x⁴ + 0.5 x³ y + 1.75 x² y² + 0.5 x y³ - 0.125 y⁴ - 0.125 x⁵ - 0.125 x⁴ y + 1.75 x³ y² + 1.75 x² y³ - 0.125 x y⁴ - 0.125 y⁵ - 0.0625 x⁶ - 0.5 x⁵ y + 0.8125 x⁴ y² + 3.0 x³ y³ + 0.8125 x² y⁴ - 0.5 x y⁵ - 0.0625 y⁶ + 𝒪(‖x‖⁷)

julia> evaluate(f, [1, 1])
14.0

Obviously, I'm expecting a value of 1/2 when I evaluate f = 1 / (1^2 + 1^2) so I know something is wrong here. I've tried a few tweaks to no avail. I'm sure this is either something really simple that I'm doing wrong in the syntax/setup of the problem and would greatly appreciate someone pointing out the correct way to set this up.

**Comment by lbenet** [comment]
Hi,

first of all, thanks for your interest in TaylorSeries. Please, if you find (here or elsewhere) that something is unclear, send us a PR to clarify it.

Actually, the result is correct, but the subtlety is what are you aiming at. So, I'll reproduce what you did (with small changes which are not important), and add some comments; I am using current master, though the last tagged version should yield the same.

```julia
julia> using TaylorSeries

julia> f(x,y) = 1/(x^2+y^2)
f (generic function with 1 method)

julia> δx, δy = set_variables("δx δy")
2-element Array{TaylorSeries.TaylorN{Float64},1}:
  1.0 δx + 𝒪(‖x‖⁷)
  1.0 δy + 𝒪(‖x‖⁷)

julia> ff = f(1.0+δx, 1.0+δy)
 0.5 - 0.5 δx - 0.5 δy + 0.25 δx² + 1.0 δx δy + 0.25 δy² - 1.0 δx² δy - 1.0 δx δy² - 0.125 δx⁴ + 0.5 δx³ δy + 1.75 δx² δy² + 0.5 δx δy³ - 0.125 δy⁴ + 0.125 δx⁵ + 0.125 δx⁴ δy - 1.75 δx³ δy² - 1.75 δx² δy³ + 0.125 δx δy⁴ + 0.125 δy⁵ - 0.0625 δx⁶ - 0.5 δx⁵ δy + 0.8125 δx⁴ δy² + 3.0 δx³ δy³ + 0.8125 δx² δy⁴ - 0.5 δx δy⁵ - 0.0625 δy⁶ + 𝒪(‖x‖⁷)
```

So far, except for some signs, we got essentially the same. The sign differences arise because I did the shift x -> 1+δx (and something similar for y), while you did something different (a shift to -1,-1), but this is no essential problem due to the symmetry. 

What I'd like to emphasize with the change of notation from `x` to `δx`, is that `δx` is actually small. So, if you want to get the value of f(x=1,y=1) after the shift, which is the expected 0.5, you should evaluate f(1+δx, 1+δy) at δx=δy=0, which is the constant term of the result above, just as you expect it.

```julia
julia> evaluate(ff, [0.0,0.0])
0.5
```

Simply, recall that `δx` and `δy` are supposed to be small enough, which is actually defined by the convergence properties of the series, and where you cut it.

**Comment by lbenet** [comment]
@jman87 Did my comment solved the issue?

**Comment by jman87** [comment]
Thank @lbenet  That was a big help. Feel a little silly that I didn't see my mistake now, but your explanation was excellent.
