### ISSUE TITLE
Package compatibility caps

### ISSUE THREAD

**Issue by KZiemian** [JuliaDiff/TaylorSeries.jl#182]
Ref: https://discourse.julialang.org/t/package-compatibility-caps/15301

**Comment by lbenet** [comment]
Thanks for reporting! 

Do you mean that it has been caped? I checked yesterday that discussion, and due to "claims to support ≥ 0.7 & tagged on July 14 or later => 1.0 compatible" I thought it was ok. `TaylorSeries` v0.8.0 does support Julia ≥ 0.7 and was tagged around two or three weeks ago.

Could you confirm it has been tagged? What system do you use?

**Comment by dpsanders** [comment]
This seems to be FUD.

**Comment by dpsanders** [comment]
@KZiemian Please stop opening these issues everywhere without checking if there is actually an issue with the package having been capped.
