### ISSUE TITLE
Support `asinh, acosh, atanh`.

### ISSUE THREAD

**Issue by Jollywatt** [JuliaDiff/TaylorSeries.jl#261]
The three inverse hyperbolic functions `asinh, acosh, atanh` are the only trig functions yet to be implemented.

Once these are defined on series, Julia’s full suite of standard trig functions

    sin, cos, tan, asin, acos, atan, sinh, cosh, tanh, asinh, acosh, atanh, csc, sec, cot, acsc, asec, acot, csch, sech, coth, acsch, asech, acoth

will be supported, thanks to the default definitions like `acsch(x::Number) = inv(asinh(x))` in `Base`.

This should be an easy fix. (I would make a PR myself, but the actual code in `functions.jl` is a bit obscure…)

**Comment by lbenet** [comment]
Thanks for opening this issue! You are right, we should add those functions. It would be great if you can make the PR!

At the moment I can't guide you through what exactly one has to do, but I'll try to get back on this on Monday. Let me only say that you should first obtain the *recurrence relation* for the specific elementary function, such as those provided [in the docs](http://www.juliadiff.org/TaylorSeries.jl/stable/background/#Elementary-functions-of-polynomials). 

How do you do that? You first propose an ordinary differential equation (initial value problem) whose solution is the function you look for, e.g., `asinh(g(t))`, where `g(t)` is a (Taylor) polynomial. You propose a polynomial solution, which you solve *order by order*; that precisely yields the recurrence relation. I suggest that you try it first for the `exp`  function, because it  is simpler and it clarifies how to do it (and the answer is there), and then get to the more difficult problems.

Regarding the obscurity of the code (truly sorry!), this is related to the possibility of calling the functions that compute the recurrence relations directly. This is important for us in [TaylorIntegration.jl](https://github.com/PerezHz/TaylorIntegration.jl) to optimize the performance.

**Comment by mforets** [comment]
> This should be an easy fix. (I would make a PR myself, but the actual code in functions.jl is a bit obscure…)

I would encourage that you don't get intimidated with the code and ask direct questions about the package internals and such -- so you can contribute and learn thins along the way ;) The code patterns being used in that file are not uncommon: (i) implement an in-place version of the function for efficiency, but expose the out-of-place version; (ii) use macros to reduce the LOC (for the latter you may find the section on [code generation](https://docs.julialang.org/en/v1/manual/metaprogramming/#Code-Generation) useful).

**Comment by Jollywatt** [comment]
Well, I went down the rabbit hole and reached the bottom! I’ve made PR #262.

Some things that should be double-checked:

- I believe the new entries in `dictmutfunct.jl` for `asinh`, `acosh`, `atanh` are correct, but I don’t know how to test them.
- The `ArgumentError` messages thrown by `asinh`, `acosh`, `atanh` at singularities aren’t really helpful or consistent.
