### ISSUE TITLE
!(iszero(constant_term(b)))

### ISSUE THREAD

**Issue by liushang0322** [JuliaDiff/TaylorSeries.jl#290]
Maybe there is a bug in this pkg
z = set_variables("z",order = 5)
1/tan(z[1])
ERROR: AssertionError: !(iszero(constant_term(b)))

**Comment by lbenet** [comment]
Thanks for reporting. That's not a bug, but a consequence of the fact that you are expanding something of the form `1/(x+...)` around zero, as you can check:
```julia
julia> tan(z[1])
 1.0 z + 0.3333333333333333 z³ + 0.13333333333333333 z⁵ + 𝒪(‖x‖⁶)
```
Since the first element (the constant term) of `tan(z[1])` is zero, its inverse would be `Inf` and the expansion makes no sense.

**Comment by lbenet** [comment]
As a side remark, if you are considering Taylor expansion in one variable, it's better to use `Taylor1` instad of `TaylorN`, because some tricks (factorizations) are implemented which are difficult to handle in general with `TaylorN`; also, performance is better. 

I guess your example is an MWE and the actual application involves more variables...
