### ISSUE TITLE
sqrt at zero

### ISSUE THREAD

**Issue by mongibellili** [JuliaDiff/TaylorSeries.jl#302]
This is more of a question than an issue. I understand why expanding the sqrt around zero throws the error (derivative), but I am trying to build an application using the Taylorseries.jl and I need to use sqrt(t), where t is Taylor1, since sqrt(0) is defined unlike for example log(0). any advice on how i should proceed? also is there a place where the sqrt! code is explained?
thank you for your time.

**Comment by lbenet** [comment]
Thanks for reaching out and for your question! I'm not sure the following answers the question, so I'll try to guide you through the code, and indicate where you can modify something.

`sqrt(::Taylor1)` executes [this line](https://github.com/JuliaDiff/TaylorSeries.jl/blob/c83da89375ddf36a1534e631aea2aae811eb0f38/src/power.jl#L359). The first code block checks where the first non-zero coefficient of the Taylor1 polynomial is located; that is actually where the error is thrown, since for `t=Taylor1(5)` the first non-zero coefficient in this case is odd. The reason to distinguish odd and even first non-zero coefficients is, essentially, to be able to factor an expression of the form $\sqrt{t^{2n* p(t)}} = t^n*\sqrt{p(t)}$, with $p(t)$ a polynomial with non-zero 0-th order coefficient.

The next code block computes order by order the Taylor expansion. It uses `sqrt!` to update (modify in place) the Taylor coefficient of order `k` of `c`, which is the returned result. `sqrt!` is coded [here](https://github.com/JuliaDiff/TaylorSeries.jl/blob/c83da89375ddf36a1534e631aea2aae811eb0f38/src/power.jl#L425), and you can check the docstrings [here](https://juliadiff.org/TaylorSeries.jl/stable/api/#TaylorSeries.sqrt!) or in the REPL (`? TaylorSeries.sqrt!`). The function essentially implements the relevant formula (which does not appear properly displayed as it should in the documentation). 

Let me point out that `sqrt!` throws no error, that `sqrt(::Taylor1)` computes the 0-th order coefficient [separatelly](https://github.com/JuliaDiff/TaylorSeries.jl/blob/c83da89375ddf36a1534e631aea2aae811eb0f38/src/power.jl#L376), and that the rest of the coefficients are computed using `sqrt!`. So, if you want to code your own `mysqrt`, you should perhaps compute the Taylor expansion using `sqrt!` directly, including the first non-zero coefficient. Be aware that `Inf`s and `NaN`s may propagate in the series, because the computation is recursive. This means that `mysqrt(t)` may return something like `Inf t - Inf t² + Inf t³ - Inf t⁴ + Inf t⁵ + 𝒪(t⁶)`.

I hope this is useful for your application.

**Comment by lbenet** [comment]
Closing. Feel free to reopen this issue if you want further explanations..
