### ISSUE TITLE
order of the remainder

### ISSUE THREAD

**Issue by qwertyjl** [JuliaDiff/TaylorSeries.jl#306]
```julia
t = Taylor1(7)
sin(t) # ... + 𝒪(t⁸)
```
Shouldn't the remainder be `𝒪(t⁹)`?
Is there any way to get the correct order of the remainder even if it is greater than the order of the previously defined variable t?

**Comment by lbenet** [comment]
I think the output is correct from your definition of `t`, which is of order 7. 

Let me put it in this way: If you *truncate* a series to order $n$, you know a priori nothing of the term $n+1$, hence the notation $\mathcal{O}^{n+1}$. This holds for `sin(t)` but also for the `t` variable, since the latter is a `Taylor1` object and therefore has a finite order expansion. 

Mathematically, $t$ is known to infinite precision, so for "simple" functions such as $sin$ we know everything. Yet `t` is a finite representation of the mathematical $t$, and we try to be consequent.
