### ISSUE TITLE
sqrt gives misleading O() term

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/TaylorSeries.jl#58]
```
julia> t = Taylor1(10)
 1.0 t + 𝒪(t¹¹)

julia> sqrt(t^2 + t^3)
 1.0 t + 0.5 t² - 0.125 t³ + 0.0625 t⁴ - 0.0390625 t⁵ + 0.02734375 t⁶ - 0.0205078125 t⁷ + 0.01611328125 t⁸ + 𝒪(t¹¹)
```

This seems to imply that the t^9 and t^10 terms have zero coefficients, which is incorrect.

**Comment by lbenet** [comment]
I agree with the observation; it is misleading, though consistent with the implementation. The point is somewhat subtle, so be patient with my explanation :-)

If you develop `sqrt(t)` around 0, you have an issue, since at zero the first derivative is infinite. In the expansion this shows up at the recurrence relation which involves a division by zero (the zero-th order coefficient of the argument of the sqrt appears in the denominator). So far, things are consistent.

Something alike *would* happen for `sqrt(t^2)`, but in this case we know that the result is simply t. The idea in this case (and its generalizations) is factorize t^2, and compute the expansion of `t*sqrt(p(t))`, here t^2*p(t) is the original argument of the `sqrt`. The subtlety is that t^2*p(t) is a polynomial of order 10, so p(t) is a polynomial of order 8, and you have no way of knowing what are the coefficients of order 9 and 10 for p(t).

If you want to get a *better* expansion, you should factorize t^2 by yourself and then expand:
```julia
julia> t*sqrt(1+t)
 1.0 t + 0.5 t² - 0.125 t³ + 0.0625 t⁴ - 0.0390625 t⁵ + 0.02734375 t⁶ - 0.0205078125 t⁷ + 0.01611328125 t⁸ - 0.013092041015625 t⁹ + 0.0109100341796875 t¹⁰ + 𝒪(t¹¹)
```

**Comment by lbenet** [comment]
The implementation of the *correct* expansion could be done, but then we have to determine automatically and extension in the order of the polynomials to get the correct expansion.

**Comment by dpsanders** [comment]
I guess my point was that `sqrt(t^2 + t^3)` should somehow warn you that it had lost the higher-order information, e.g. by reducing the error to `O(t^9)` or whatever.

**Comment by lbenet** [comment]
We deleted such warning a while back. Maybe it is better to the the automatic extension (if it is possible) and return the correct result.
