### ISSUE TITLE
update! functionality

### ISSUE THREAD

**Issue by BenLauwens** [JuliaDiff/TaylorSeries.jl#80]
Hi

Often when I work with TaylorSeries, I need to update the coefficients of a TaylorSeries around a next point.
A very convenient feature would be an update! function.
Example:
`x = Taylor1([1.0, 2.0, 3.0])`
`update!(x, 1.0)`
where the result would give for `x`
`6+8t+3t^2+O(t^3)`
As a workaround I am using for the moment
`t = Taylor1[1.0, 1.0]`
`x = evaluate(x, t)`
Looking at the code some optimization in update! is possible. A generalized Horner procedure can do this efficiently. If there is some interest, I will post tomorrow a possible implementation.

**Comment by lbenet** [comment]
Hi,
first of all, let me apologize because I just noticed today your issue, which is already two weeks old. (Somehow, github notifications not always manage to get to my email.)

If I understand it correctly your idea, `update!(x, 1.0)` corresponds to `evaluate(x,1.0+Taylor1(1))`, so some kind of shift of the point were you are computing the Taylor expansion. (Note that this may not be an optimized version.) Please, do send a pull request with your implementation, with documentation, and I'll merge it. The only thing which may be a bit misleading is the name of the function.

**Comment by lbenet** [comment]
This has been addressed and implemented in #121. I'm thus closing this.
