### ISSUE TITLE
sin for TaylorN seems to be broken

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/TaylorSeries.jl#81]
```
julia> s = (x + y)^5
 1.0 x⁵ + 5.0 x⁴ y + 10.0 x³ y² + 10.0 x² y³ + 5.0 x y⁴ + 1.0 y⁵ + 𝒪(‖x‖⁷)

julia> s = sin((x + y)^5)
 1.0 x⁵ + 5.0 x⁴ y + 10.0 x³ y² + 10.0 x² y³ + 5.0 x y⁴ + 1.0 y⁵ + 𝒪(‖x‖⁷)
```

**Comment by lbenet** [comment]
The result is correct, since you are expanding up to order 6.  In a sense, what you are seeing are the lowest order corrections because higher corrections are beyond the maximum order of `TaylorN` (order 6 in this case). This is so because `(x+y)^5` is an homogeneous polynomial of order 5, `sin((x+y)^5` contains all such terms ("first order"). The next order contains terms that are cubics of the monomials, or products of a square of a monomial with another monomial. In either case, such corrections are polynomials of order 15, which is well beyond order 6.

```julia
julia> x, y = set_variables("x y", order=16)
2-element Array{TaylorSeries.TaylorN{Float64},1}:
  1.0 x + 𝒪(‖x‖¹⁷)
  1.0 y + 𝒪(‖x‖¹⁷)

julia> sin((x+y)^5)
 1.0 x⁵ + 5.0 x⁴ y + 10.0 x³ y² + 10.0 x² y³ + 5.0 x y⁴ + 1.0 y⁵ - 0.16666666666666666 x¹⁵ - 2.5 x¹⁴ y - 17.5 x¹³ y² - 75.83333333333333 x¹² y³ - 227.5 x¹¹ y⁴ - 500.5 x¹⁰ y⁵ - 834.1666666666666 x⁹ y⁶ - 1072.5 x⁸ y⁷ - 1072.5 x⁷ y⁸ - 834.1666666666666 x⁶ y⁹ - 500.5 x⁵ y¹⁰ - 227.5 x⁴ y¹¹ - 75.83333333333333 x³ y¹² - 17.5 x² y¹³ - 2.5 x y¹⁴ - 0.16666666666666666 y¹⁵ + 𝒪(‖x‖¹⁷)
```

**Comment by dpsanders** [comment]
Oops, good point, thanks!
